### PR TITLE
[Devtools/Objectinspector] Filter 

### PR DESCRIPTION
**Pull request by lexfm**
### Change Type (required)
Updated @devtools-ui/plugin to version `0.3.0`, in order to show an object prop path filter in the Devtools plugin browser Flow panel.

- [x] `patch`
- [ ] `minor`
- [ ] `major`

<details>
  <summary>📦 Published PR as canary version: <code>0.6.1--canary.121.2815</code></summary>
  <br />

  Try this version out locally by upgrading relevant packages to 0.6.1--canary.121.2815
</details>

### CODE REVIEW

**Review by KetanReddy — CHANGES_REQUESTED** [review]
Commits need to be signed.

**Comment by lexfm** [comment]
Closed in favor of signing commits.

**Pull request closed without merging**
